cask_args appdir: "/Applications"

# Applications
cask "airserver"
cask "cyberduck"
cask "handbrake"
cask "hazel"
cask "karabiner-elements"
cask "skype"
cask "spotify"
cask "teamviewer"
cask "tokens"
cask "vlc"
